services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kamangir-api
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      SECRET: ${SECRET}
      MERCHANT_CODE: ${MERCHANT_CODE}
      DB_URL: ${DB_URL}

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mariadb_data:
